### ISSUE TITLE
Will you be adding these to spacemacs?

### ISSUE THREAD

**Issue by ghost** [TheBB/spacemacs-layers#1]
Or upstream for that matter?

When I tried the indentation stuff it seemed deeply broken, so I forgot all about it.

It did not even understand simple stuff like that two lines could have an empty line in between them and still be at the same indentation (in Python even, which is very strict about indentation).

**Comment by TheBB** [comment]
In general I won't pursue it, but the indentation text objects really are hopeless, so we should have a discussion about that one, I guess. See https://github.com/syl20bnr/spacemacs/issues/2326

I kind of gave up on `evil-indent-textobject` upstream, but it could be worth trying again.

**Comment by TheBB** [comment]
The fork of `evil-indent-textobjects` is now in Spacemacs develop, so I'll delete that layer from here.
