### ISSUE TITLE
Help about  the colored bar on the right side in org-mode expanded outlines

### ISSUE THREAD

**Issue by nujabse** [TheBB/spacemacs-layers#2]
![screenshot from 2016-04-20 20-19-22](https://cloud.githubusercontent.com/assets/9455367/14674169/36ee6290-0735-11e6-9e79-267c34d7decd.png)
Hi! I'm a spacemacs newcomer, and fell in love with it when I watched the Spaemacs abc series on youtube. Could you explain how to add the vertical colored bars on the buffer right edge in org mode, just like what looks like in the picture above? Thanks!

**Comment by TheBB** [comment]
Hi,

Please see the [documentation](http://spacemacs.org/layers/+source-control/version-control/README.html) for the version-control layer. The diff you are seeing is produced by the `diff-hl` margin tool, so you have to set `version-control-diff-tool` to that.

Like [here](https://github.com/TheBB/spacemacs-layers/blob/master/init.el#L55) in my own .spacemacs file.

Note that this has nothing to do with org-mode.

**Comment by nujabse** [comment]
Wonderful! Thank you for your quick and useful reply, that really worked!
