### ISSUE TITLE
,bb/full-name

### ISSUE THREAD

**Issue by ralfr** [TheBB/spacemacs-layers#4]
Sorry if this might be a newbie question, but in your inet.el file, you've got this line:

``(("irc.gitter.im" :port "6667" :nick "TheBB" :full-name ,bb/full-name
      :ssl t :password ,bb/gitter-pwd)`

I'm wondering, where does the `,bb/full-name` and `,bb/gitter-pwd` come from.

**Comment by TheBB** [comment]
From here: https://github.com/TheBB/spacemacs-layers/blob/master/init.el#L434-L435

My private information isn't in this repo. Although my name probably could be (it's not hard to find). The password must be secret however.

**Comment by ralfr** [comment]
Thanks! I'm not at all into Emacs Lisp, yet. Could you paste the contents of local.el, anonymised obviously. But that way, I can replicate your setup with my credentials.

**Comment by TheBB** [comment]
I mean it's just

``` elisp
(setq bb/gitter-pwd "...")
(setq bb/full-name "...")
```

**Comment by ralfr** [comment]
Thanks! And thanks for the awesome work you do and contribute back to the community.

**Comment by TheBB** [comment]
You're welcome.
